export const photoData = [
    {
        id: '',
        path: '',
        note: '',
        url: '',
        detail: '',
        plan: '',
        budget: null,
        large: '',
        pref: '',
        town: '',
        brand: '',
        event: false,
        category: '',
        shop: '',
        staff: '',
        tag: []
    }, {
        id: 'sample1',
        path: 'https://kh-house.jp/owners_house/img/owners/house_2/img_1.jpg',
        note: 'ワンフロアで完結し、自然と家族がつながる心地よい空間。',
        url: 'https://kh-house.jp/owners_house/owners?id=00000006',
        detail: '外観',
        plan: '平屋',
        budget: 2500,
        large: '30坪',
        pref: '鹿児島県',
        town: '鹿児島市',
        brand: 'なごみ工務店',
        event: true,
        category: 'オーナーズハウス',
        shop: '鹿児島店',
        staff: '中脇',
        tag: ['BBQができる庭', '広々LDK']
    }, {
        id: 'sample2',
        path: 'https://kh-house.jp/wp-content/uploads/2026/02/S1A0040-scaled.jpg',
        note: '生活動線が短く、毎日の家事が驚くほどスムーズになる住まい。',
        url: '',
        detail: '外観',
        plan: '平屋',
        budget: 2400,
        large: '29坪',
        pref: '鹿児島県',
        town: '出水市',
        brand: '国分ハウジング',
        event: true,
        category: '施工事例',
        shop: '出水阿久根店',
        staff: '森吉',
        tag: ['勾配天井', '小上がり', '和室']
    },{
        id: 'sample3',
        path: 'https://kh-house.jp/wp-content/uploads/2026/02/S1A0075-scaled.jpg',
        note: '外との距離が近く、四季の移ろいを身近に感じられる住まい。',
        url: '',
        detail: '外観',
        plan: '平屋',
        budget: 2400,
        large: '29坪',
        pref: '鹿児島県',
        town: '出水市',
        brand: '国分ハウジング',
        event: true,
        category: '施工事例',
        shop: '出水阿久根店',
        staff: '森吉',
        tag: ['勾配天井', '小上がり', '和室']
    },{
        id: 'sample4',
        path: 'https://kh-house.jp/owners_house/img/owners/house_1/img_3.jpg',
        note: '将来まで安心して暮らせる、段差の少ないフラットな生活空間。',
        url: 'https://kh-house.jp/owners_house/owners?id=00000001',
        detail: '内観',
        plan: '平屋',
        budget: 2200,
        large: '31坪',
        pref: '鹿児島県',
        town: '鹿屋市',
        brand: '国分ハウジング',
        event: true,
        category: 'オーナーズハウス',
        shop: '鹿屋店',
        staff: '迫',
        tag: ['勾配天井', 'BBQのできる庭', 'シアタールーム']
    },{
        id: 'sample5',
        path: 'https://kh-house.jp/wp-content/uploads/2022/02/IMG_3147-1.jpg',
        note: '',
        url: 'https://kh-house.jp/modelhouse/217',
        detail: '外観',
        plan: '2階建て',
        budget: null,
        large: '38坪',
        pref: '鹿児島県',
        town: '鹿児島市',
        brand: '国分ハウジング',
        event: true,
        category: 'モデルハウス',
        shop: '鹿児島店',
        staff: '',
        tag: ['吹き抜け', '和室', 'シアタールーム']
    },{
        id: 'sample6',
        path: 'https://kh-house.jp/owners_house/img/owners/house_1/img_5.jpg',
        note: '天井を高く取りやすく、開放感あふれる広々とした暮らしを実現。',
        url: 'https://kh-house.jp/owners_house/owners?id=00000001',
        detail: '内観',
        plan: '平屋',
        budget: 2650,
        large: '31坪',
        pref: '鹿児島県',
        town: '霧島市',
        brand: '国分ハウジング',
        event: true,
        category: 'オーナーズハウス',
        shop: '姶良店',
        staff: '',
        tag: ['吹き抜け', '和室', 'シアタールーム']
    },{
        id: 'sample7',
        path: 'https://kh-house.jp/wp-content/uploads/2025/07/%E5%A4%96%E8%A6%B3-2048x1365.png',
        note: '上下移動がなく、子育ても老後も快適に過ごせるやさしい住まい。',
        url: '',
        detail: '外観',
        plan: '平屋',
        budget: 2350,
        large: '32坪',
        pref: '宮崎県',
        town: '宮崎市',
        brand: '国分ハウジング',
        event: false,
        category: '施工事例',
        shop: '宮崎店',
        staff: '',
        tag: ['吹き抜け', '和室', 'シアタールーム']
    },{
        id: 'sample8',
        path: 'https://www.ie-miru.jp/rails/active_storage/blobs/eyJfcmFpbHMiOnsiZGF0YSI6Mjc5MjUwMSwicHVyIjoiYmxvYl9pZCJ9fQ==--96476d88a2691c1aa508bf12f1c5a57fa73434cf/%E5%AF%9D%E5%AE%A4.png',
        note: '寝室にはこだわりのロフト空間。収納空間としても趣味スペースとしても活用可能です！',
        url: 'https://www.ie-miru.jp/cms/yoyaku/khsaga/events/120488?kc_source=kh-house.jp/&utm_store_kc=true&header_back_url=https://kh-house.jp/&_gl=1*1dp9dxq*_gcl_aw*R0NMLjE3NzM4ODA1MjcuQ2owS0NRandtdW5OQmhEYkFSSXNBT25kS3BseHV2UWZjUldjZHRUOVF3T2YzUmc5dTdrSGVqbE5wME51SmJoeGJYTDRnc2w0ZDBqZXJFVWFBclpPRUFMd193Y0I.*_gcl_au*MTcwMjA1NTIzMC4xNzY5OTk2NTM4LjI5MjI4ODM0Mi4xNzczODk1NzQ2LjE3NzM4OTU3NDU.*_ga*MTQ0MzY5NDY3NS4xNzcyNzE5MzE4*_ga_ZXLB7RRYN0*czE3NzQxNzExMDEkbzExNSRnMSR0MTc3NDE3MTEwMSRqNjAkbDAkaDA.',
        detail: '内観',
        plan: '平屋',
        budget: 2250,
        large: '31坪',
        pref: '佐賀県',
        town: '嬉野市',
        brand: '国分ハウジング',
        event: false,
        category: '完成見学会',
        shop: '佐賀店',
        staff: '',
        tag: ['吹き抜け', '和室', 'シアタールーム']
    },{
        id: 'sample9',
        path: 'https://www.relite-reform.com/wp-content/uploads/2020/04/8a6e1382e829d22a04eb2b89bcb259ca-2.jpg',
        note: '寝室にはこだわりのロフト空間。収納空間としても趣味スペースとしても活用可能です！',
        url: 'https://www.ie-miru.jp/cms/yoyaku/khsaga/events/120488?kc_source=kh-house.jp/&utm_store_kc=true&header_back_url=https://kh-house.jp/&_gl=1*1dp9dxq*_gcl_aw*R0NMLjE3NzM4ODA1MjcuQ2owS0NRandtdW5OQmhEYkFSSXNBT25kS3BseHV2UWZjUldjZHRUOVF3T2YzUmc5dTdrSGVqbE5wME51SmJoeGJYTDRnc2w0ZDBqZXJFVWFBclpPRUFMd193Y0I.*_gcl_au*MTcwMjA1NTIzMC4xNzY5OTk2NTM4LjI5MjI4ODM0Mi4xNzczODk1NzQ2LjE3NzM4OTU3NDU.*_ga*MTQ0MzY5NDY3NS4xNzcyNzE5MzE4*_ga_ZXLB7RRYN0*czE3NzQxNzExMDEkbzExNSRnMSR0MTc3NDE3MTEwMSRqNjAkbDAkaDA.',
        detail: '内観',
        plan: '平屋',
        budget: 2250,
        large: '31坪',
        pref: '佐賀県',
        town: '嬉野市',
        brand: '国分ハウジング',
        event: false,
        category: '施工事例',
        shop: '佐賀店',
        staff: '',
        tag: ['クリナップ', 'システムキッチン', 'ステディア']
    },{
        id: 'sample10',
        path: 'https://www.lixil.co.jp/lineup/kitchen/s/noctrf/pic/style_section1_pic1_pc.jpg',
        note: '寝室にはこだわりのロフト空間。収納空間としても趣味スペースとしても活用可能です！',
        url: 'https://www.ie-miru.jp/cms/yoyaku/khsaga/events/120488?kc_source=kh-house.jp/&utm_store_kc=true&header_back_url=https://kh-house.jp/&_gl=1*1dp9dxq*_gcl_aw*R0NMLjE3NzM4ODA1MjcuQ2owS0NRandtdW5OQmhEYkFSSXNBT25kS3BseHV2UWZjUldjZHRUOVF3T2YzUmc5dTdrSGVqbE5wME51SmJoeGJYTDRnc2w0ZDBqZXJFVWFBclpPRUFMd193Y0I.*_gcl_au*MTcwMjA1NTIzMC4xNzY5OTk2NTM4LjI5MjI4ODM0Mi4xNzczODk1NzQ2LjE3NzM4OTU3NDU.*_ga*MTQ0MzY5NDY3NS4xNzcyNzE5MzE4*_ga_ZXLB7RRYN0*czE3NzQxNzExMDEkbzExNSRnMSR0MTc3NDE3MTEwMSRqNjAkbDAkaDA.',
        detail: '内観',
        plan: '平屋',
        budget: 2250,
        large: '31坪',
        pref: '佐賀県',
        town: '嬉野市',
        brand: '国分ハウジング',
        event: false,
        category: '施工事例',
        shop: '佐賀店',
        staff: '',
        tag: ['リクシル', 'システムキッチン', 'ノクト']
    },{
        id: 'sample11',
        path: 'https://www.takara-standard.co.jp/img/product/homebuilder/plan_ofelia019.jpg',
        note: '調理・洗い物・収納が一体化していて、動きがスムーズになる。',
        url: 'https://www.ie-miru.jp/cms/yoyaku/khsaga/events/120488?kc_source=kh-house.jp/&utm_store_kc=true&header_back_url=https://kh-house.jp/&_gl=1*1dp9dxq*_gcl_aw*R0NMLjE3NzM4ODA1MjcuQ2owS0NRandtdW5OQmhEYkFSSXNBT25kS3BseHV2UWZjUldjZHRUOVF3T2YzUmc5dTdrSGVqbE5wME51SmJoeGJYTDRnc2w0ZDBqZXJFVWFBclpPRUFMd193Y0I.*_gcl_au*MTcwMjA1NTIzMC4xNzY5OTk2NTM4LjI5MjI4ODM0Mi4xNzczODk1NzQ2LjE3NzM4OTU3NDU.*_ga*MTQ0MzY5NDY3NS4xNzcyNzE5MzE4*_ga_ZXLB7RRYN0*czE3NzQxNzExMDEkbzExNSRnMSR0MTc3NDE3MTEwMSRqNjAkbDAkaDA.',
        detail: '内観',
        plan: '平屋',
        budget: 2250,
        large: '31坪',
        pref: '佐賀県',
        town: '嬉野市',
        brand: '国分ハウジング',
        event: false,
        category: '施工事例',
        shop: '佐賀店',
        staff: '',
        tag: ['リクシル', 'システムキッチン', 'オフェリア']
    },{
        id: 'sample12',
        path: 'https://www.lixil.co.jp/lineup/kitchen/richelle/pic/richelle-img-sp.jpg',
        note: '天板やシンクがフラットで、汚れが溜まりにくい構造。',
        url: 'https://www.ie-miru.jp/cms/yoyaku/khsaga/events/120488?kc_source=kh-house.jp/&utm_store_kc=true&header_back_url=https://kh-house.jp/&_gl=1*1dp9dxq*_gcl_aw*R0NMLjE3NzM4ODA1MjcuQ2owS0NRandtdW5OQmhEYkFSSXNBT25kS3BseHV2UWZjUldjZHRUOVF3T2YzUmc5dTdrSGVqbE5wME51SmJoeGJYTDRnc2w0ZDBqZXJFVWFBclpPRUFMd193Y0I.*_gcl_au*MTcwMjA1NTIzMC4xNzY5OTk2NTM4LjI5MjI4ODM0Mi4xNzczODk1NzQ2LjE3NzM4OTU3NDU.*_ga*MTQ0MzY5NDY3NS4xNzcyNzE5MzE4*_ga_ZXLB7RRYN0*czE3NzQxNzExMDEkbzExNSRnMSR0MTc3NDE3MTEwMSRqNjAkbDAkaDA.',
        detail: '内観',
        plan: '平屋',
        budget: 2250,
        large: '31坪',
        pref: '佐賀県',
        town: '嬉野市',
        brand: '国分ハウジング',
        event: false,
        category: '施工事例',
        shop: '佐賀店',
        staff: '',
        tag: ['リクシル', 'システムキッチン', 'リシェル']
    },{
        id: 'sample12',
        path: 'https://www.takara-standard.co.jp/img/product/system_kitchen/treasia/design_bg_04.jpg',
        note: '寝室にはこだわりのロフト空間。収納空間としても趣味スペースとしても活用可能です！',
        url: 'https://www.ie-miru.jp/cms/yoyaku/khsaga/events/120488?kc_source=kh-house.jp/&utm_store_kc=true&header_back_url=https://kh-house.jp/&_gl=1*1dp9dxq*_gcl_aw*R0NMLjE3NzM4ODA1MjcuQ2owS0NRandtdW5OQmhEYkFSSXNBT25kS3BseHV2UWZjUldjZHRUOVF3T2YzUmc5dTdrSGVqbE5wME51SmJoeGJYTDRnc2w0ZDBqZXJFVWFBclpPRUFMd193Y0I.*_gcl_au*MTcwMjA1NTIzMC4xNzY5OTk2NTM4LjI5MjI4ODM0Mi4xNzczODk1NzQ2LjE3NzM4OTU3NDU.*_ga*MTQ0MzY5NDY3NS4xNzcyNzE5MzE4*_ga_ZXLB7RRYN0*czE3NzQxNzExMDEkbzExNSRnMSR0MTc3NDE3MTEwMSRqNjAkbDAkaDA.',
        detail: '内観',
        plan: '平屋',
        budget: 2250,
        large: '31坪',
        pref: '佐賀県',
        town: '嬉野市',
        brand: '国分ハウジング',
        event: false,
        category: '施工事例',
        shop: '佐賀店',
        staff: '',
        tag: ['タカラスタンダード', 'システムキッチン', 'トレーシア']
    },{
        id: 'sample13',
        path: 'https://www.lixil.co.jp/lineup/entrance/giesta/pic/giesta_img_02.jpg',
        note: '寝室にはこだわりのロフト空間。収納空間としても趣味スペースとしても活用可能です！',
        url: 'https://www.ie-miru.jp/cms/yoyaku/khsaga/events/120488?kc_source=kh-house.jp/&utm_store_kc=true&header_back_url=https://kh-house.jp/&_gl=1*1dp9dxq*_gcl_aw*R0NMLjE3NzM4ODA1MjcuQ2owS0NRandtdW5OQmhEYkFSSXNBT25kS3BseHV2UWZjUldjZHRUOVF3T2YzUmc5dTdrSGVqbE5wME51SmJoeGJYTDRnc2w0ZDBqZXJFVWFBclpPRUFMd193Y0I.*_gcl_au*MTcwMjA1NTIzMC4xNzY5OTk2NTM4LjI5MjI4ODM0Mi4xNzczODk1NzQ2LjE3NzM4OTU3NDU.*_ga*MTQ0MzY5NDY3NS4xNzcyNzE5MzE4*_ga_ZXLB7RRYN0*czE3NzQxNzExMDEkbzExNSRnMSR0MTc3NDE3MTEwMSRqNjAkbDAkaDA.',
        detail: '内観',
        plan: '平屋',
        budget: 2250,
        large: '31坪',
        pref: '佐賀県',
        town: '嬉野市',
        brand: '国分ハウジング',
        event: false,
        category: '施工事例',
        shop: '佐賀店',
        staff: '',
        tag: ['リクシル', '玄関ドア', 'トレーシア']
    }];