export const tagList = [
  { label: '平屋', word: 'ひらやヒラヤhiraya' },
  { label: '2階', word: 'にかいニカイnikai2kai' },
  { label: 'エクステリア', word: 'えくすてりあエクステリアekusuteria' },
  { label: 'LDK全景', word: 'えるでぃーけーぜんけいエルディーケーゼンケイerudi-ke-zenkeildkzenkeildk' },
  { label: 'リビング', word: 'りびんぐリビングribingu' },
  { label: 'ダイニングキッチン', word: 'だいにんぐきっちんダイニングキッチンdainingukitchin' },
  { label: '和室', word: 'わしつワシツwashitsu' },
  { label: 'スキップフロア（ロフト）', word: 'すきっぷふろあろふとスキップフロアロフトsukippufuroarofuto' },
  { label: '天井（勾配・下げ・吹き抜け）', word: 'てんじょうこうばいさげふきぬけテンジョウコウバイサゲフキヌケtenjoukoubaisagefukinuke' },
  { label: '洗面所', word: 'せんめんじょセンメンジョsenmenjo' },
  { label: 'ランドリールーム', word: 'らんどりーるーむランドリールームrandori-ru-mu' },
  { label: 'トイレ', word: 'といれトイレtoire' },
  { label: '浴槽', word: 'よくそうヨクソウyokusou' },
  { label: 'フリースペース', word: 'ふりーすぺーすフリースペースfuri-supe-su' },
  { label: '居室', word: 'きょしつキョシツkyoshitsu' },
  { label: '収納', word: 'しゅうのうシュウノウshuunou' },
  { label: '玄関・土間・ポーチ', word: 'げんかんどまぽーちゲンカンドマポーチgenkandomapo-chi' },
  { label: '造作', word: 'ぞうさくゾウサクzousaku' },
  { label: '外観', word: 'がいかんガイカンgaikan' },
  { label: '室内ドア', word: 'しつないどあシツナイドアshitsunaidoa' },
  { label: 'シンプルモダン', word: 'しんぷるもだんシンプルモダンshinpurumodan' },
  { label: 'ナチュラル', word: 'なちゅらるナチュラルnachuraru' },
  { label: 'ホテルライク', word: 'ほてるらいくホテルライクhoteruraiku' },
  { label: '北欧テイスト', word: 'ほくおうていすとホクオウテイストhokuouteisuto' },
  { label: 'インダストリアル', word: 'いんだすとりあるインダストリアルindasutoriaru' },
  { label: '和モダン', word: 'わもだんワモダンwamodan' },
  { label: 'ペットと暮らす', word: 'ぺっととくらすペットトクラスpettotokurasu' },
  { label: '趣味と暮らす', word: 'しゅみとくらすシュミトクラスshumitokurasu' },
  { label: '店舗併用住宅', word: 'てんぽへいようじゅうたくテンポヘイヨウジュウタクtenpoheiyoujuutaku' },
  { label: '二世帯住宅', word: 'にせたいじゅうたくニセタイジュウタクnisetaijuutaku' }
];

// export const tagList = [
//     // タカラスタンダード
//     { label: 'タカラスタンダード', word: 'たからすたんだーどタカラスタンダードtakarasutandaado' },
//     { label: 'レミュー', word: 'れみゅーレミューremyuu' },
//     { label: 'トレーシア', word: 'とれーしあトレーシアtoreeshia' },
//     { label: 'エーデル', word: 'えーでるエーデルeederu' },
//     { label: 'リフィット', word: 'りふぃっとリフィットrifitto' },
//     { label: 'プレデンシア', word: 'ぷれでんしあプレデンシアpuredenshia' },
//     { label: 'グランスパ', word: 'ぐらんすぱグランスパguransupa' },
//     { label: 'エメロード', word: 'えめろーどエメロードemeroodo' },
//     { label: 'ファミーユ', word: 'ふぁみーゆファミーユfamiiyu' },
//     { label: 'オンディーヌ', word: 'おんでぃーぬオンディーヌondiinu' },
//     { label: 'ティモニ', word: 'てぃもにティモニtimoni' },

//     // LIXIL（リクシル）
//     { label: 'リクシル', word: 'りくしるリクシルrikushiru' },
//     { label: 'リシェル', word: 'りしぇるリシェルrisheru' },
//     { label: 'ノクト', word: 'のくとノクトnokuto' },
//     { label: 'シエラ', word: 'しえらシエラshiera' },
//     { label: 'スパージュ', word: 'すぱーじゅスパージュsupaaju' },
//     { label: 'リデア', word: 'りであリデアridea' },
//     { label: 'ルミシス', word: 'るみしすルミシスrumishisu' },
//     { label: 'クレヴィ', word: 'くれゔぃクレヴィkurevi' },
//     { label: 'ピアラ', word: 'ぴあらピアラpiara' },
//     { label: 'オフト', word: 'おふとオフトofuto' },
//     { label: 'サティス', word: 'さてぃすサティスsatisu' },
//     { label: 'アメージュ', word: 'あめーじゅアメージュameeju' },
//     { label: 'プレアス', word: 'ぷれあすプレアスpureasu' },
//     { label: 'エコカラット', word: 'えこからっとエコカラットekokaratto' },

//     // TOTO（トートー）
//     { label: 'トートー', word: 'とーとートートーtootoo' },
//     { label: 'ザ・クラッソ', word: 'ざくらっそザクラッソzakurasso' },
//     { label: 'ミッテ', word: 'みってミッテmitte' },
//     { label: 'シンラ', word: 'しんらシンラshinra' },
//     { label: 'サザナ', word: 'さざなサザナsazana' },
//     { label: 'エスクア', word: 'えすくあエスクアesukua' },
//     { label: 'オクターブ', word: 'おくたーぶオクターブokutaabu' },
//     { label: 'サクア', word: 'さくあサクアsakua' },
//     { label: 'ドレーナ', word: 'どれーなドレーナdoreena' },
//     { label: 'ネオレスト', word: 'ねおれすとネオレストneoresuto' },
//     { label: 'ピュアレスト', word: 'ぴゅあれすとピュアレストpyuaresuto' },
//     { label: 'ウォシュレット', word: 'うぉしゅれっとウォシュレットwoshuretto' },
//     { label: 'アプリコット', word: 'あぷりこっとアプリコットapurikotto' },

//     // Panasonic（パナソニック）
//     { label: 'パナソニック', word: 'ぱなそにっくパナソニックpanasonikku' },
//     { label: 'エルクラス', word: 'えるくらすエルクラスerukurasu' },
//     { label: 'ラクシーナ', word: 'らくしーなラクシーナrakushiina' },
//     { label: 'リビングステーション', word: 'りびんぐすてーしょんリビングステーションribingusuteeshon' },
//     { label: 'ビバス', word: 'びばすビバスbibasu' },
//     { label: 'オフローラ', word: 'おふろーらオフローラofuroora' },
//     { label: 'リフォムス', word: 'りふぉむすリフォムスrifomusu' },
//     { label: 'ウツクシーズ', word: 'うつくしーずウツクシーズutsukushiizu' },
//     { label: 'シーライン', word: 'しーらいんシーラインshiirain' },
//     { label: 'アラウーノ', word: 'あらうーのアラウーノarauuno' },

//     // クリナップ
//     { label: 'クリナップ', word: 'くりなっぷクリナップkurinappu' },
//     { label: 'セントロ', word: 'せんとろセントロsentoro' },
//     { label: 'ステディア', word: 'すてでぃあステディアsutedia' },
//     { label: 'ラクエラ', word: 'らくえらラクエラrakuera' },
//     { label: 'コルティ', word: 'こるてぃコルティkoruti' },
//     { label: 'アクリアバス', word: 'あくりあばすアクリアバスakuriabasu' },
//     { label: 'ユアシス', word: 'ゆあしすユアシスyuashisu' },
//     { label: 'ティアリス', word: 'てぃありすティアリスtiarisu' },
//     { label: 'ファンシオ', word: 'ふぁんしおファンシオfanshio' },

//     // トクラス (旧ヤマハリビングテック)
//     { label: 'トクラス', word: 'とくらすトクラスtokurasu' },
//     { label: 'コラージア', word: 'こらーじあコラージアkoraajia' },
//     { label: 'ベリー', word: 'べりーベリーberii' },
//     { label: 'ビービー', word: 'びーびービービーbiibii' },
//     { label: 'ユーノ', word: 'ゆーのユーノyuuno' },
//     { label: 'エブリィ', word: 'えぶりぃエブリィeburii' },
//     { label: 'アフェット', word: 'あふぇっとアフェットafetto' },
//     { label: 'エポック', word: 'えぽっくエポックepokku' },

//     // ハウステック
//     { label: 'ハウステック', word: 'はうすてっくハウステックhausutekku' },
//     { label: 'カナリエ', word: 'かなりえカナリエkanarie' },
//     { label: 'マルーレ', word: 'まるーれマルーレmaruure' },
//     { label: 'フェリテ', word: 'ふぇりてフェリテferite' },
//     { label: 'ルクレ', word: 'るくれルクレrukure' },
//     { label: 'ココッシュ', word: 'ここっしゅココッシュkokosshu' },
//     { label: 'ラヴァーボ', word: 'らゔぁーぼラヴァーボravaabo' },

//     // ウッドワン
//     { label: 'ウッドワン', word: 'うっどわんウッドワンuddowan' },
//     { label: 'スイージー', word: 'すいーじースイージーsuiijii' },
//     { label: 'フレームキッチン', word: 'ふれーむきっちんフレームキッチンfureemukitchin' },

//     // リンナイ (Rinnai)
//     { label: 'リンナイ', word: 'りんないリンナイrinnai' },
//     { label: 'デリシア', word: 'でりしあデリシアderishia' },
//     { label: 'リッセ', word: 'りっせリッセrisse' },
//     { label: 'マイトーン', word: 'まいとーんマイトーンmaitoon' },
//     { label: 'リノコ', word: 'りのこリノコrinoko' },
//     { label: 'エコジョーズ', word: 'えこじょーずエコジョーズekojoozu' },

//     // ノーリツ (NORITZ)
//     { label: 'ノーリツ', word: 'のーりつノーリツnooritsu' },
//     { label: 'プログレ', word: 'ぷろぐれプログレpurogure' },
//     { label: 'オルシェ', word: 'おるしぇオルシェorushe' },
//     { label: 'ピアット', word: 'ぴあっとピアットpiatto' },
//     { label: 'ファミ', word: 'ふぁみファミfami' },

//     // パロマ (Paloma)
//     { label: 'パロマ', word: 'ぱろまパロマparoma' },
//     { label: 'クレア', word: 'くれあクレアkurea' },
//     { label: 'フェイシス', word: 'ふぇいしすフェイシスfeishisu' },
//     { label: 'ウィズナ', word: 'うぃずなウィズナwizuna' },
//     { label: 'リプラ', word: 'りぷらリプラripura' },

//     // その他設備系
//     { label: 'ダイキン', word: 'だいきんダイキンdaikin' },
//     { label: 'エコキュート', word: 'えこきゅーとエコキュートekokyuuto' },
//     { label: 'サンワカンパニー', word: 'さんわかんぱにーサンワカンパニーsanwakanpanii' },
//     { label: 'アイカ工業', word: 'あいかこうぎょうアイカコウギョウaikakougyou' },
//     { label: 'フィオレストーン', word: 'ふぃおれすとーんフィオレストーンfioresutoon' },

//     // --- 間取り・空間 ---
//     { label: '吹き抜け', word: 'ふきぬけフキヌケfukinuke' },
//     { label: '勾配天井', word: 'こうばいてんじょうコウバイテンジョウkoubaitenjou' },
//     { label: 'パントリー', word: 'ぱんとりーパントリーpantorii' },
//     { label: 'シューズクローク', word: 'しゅーずくろーくシューズクロークshuuzukurooku' },
//     { label: 'ファミリークローゼット', word: 'ふぁみりーくろーぜっとファミリークローゼットfamiriikuroozetto' },
//     { label: 'ウォークインクローゼット', word: 'うぉーくいんくろーぜっとウォークインクローゼットwookuinkuroozetto' },
//     { label: 'ランドリールーム', word: 'らんどりーるーむランドリールームrandoriiruumu' },
//     { label: 'サンルーム', word: 'さんるーむサンルームsanruumu' },
//     { label: '土間玄関', word: 'どまげんかんドマゲンカンdomagenkan' },
//     { label: '通り土間', word: 'とおりどまトオリドマtooridoma' },
//     { label: '小上がり和室', word: 'こあがりわしつコアガリワシツkoagariwashitsu' },
//     { label: '小上がり', word: 'こあがりコアガリkoagari' },
//     { label: 'スタディコーナー', word: 'すたでぃこーなースタディコーナーsutadikoonaa' },
//     { label: 'ワークスペース', word: 'わーくすぺーすワークスペースwaakusupeesu' },
//     { label: 'ヌック', word: 'ぬっくヌックnukku' },
//     { label: 'ロフト', word: 'ろふとロフトrofuto' },
//     { label: 'スキップフロア', word: 'すきっぷふろあスキップフロアsukippufuroa' },
//     { label: '家事動線', word: 'かじどうせんカジドウセンkajidousen' },
//     { label: '回遊動線', word: 'かいゆうどうせんカイユウドウセンkaiyuudousen' },
//     { label: '間取り', word: 'まどりマドリmadori' },

//     // --- 造作・建具 ---
//     { label: '造作洗面台', word: 'ぞうさくせんめんだいゾウサクセンメンダイzousakusenmendai' },
//     { label: '造作棚', word: 'ぞうさくだなゾウサクダナzousakudana' },
//     { label: '造作テレビボード', word: 'ぞうさくてれびぼーどゾウサクテレビボードzousakuterebiboodo' },
//     { label: 'ニッチ', word: 'にっちニッチnitchi' },
//     { label: 'マガジンラック', word: 'まがじんらっくマガジンラックmagajinrakku' },
//     { label: 'ハイドア', word: 'はいどあハイドアhaidoa' },
//     { label: 'バーチカルブラインド', word: 'ばーちかるぶらいんどバーチカルブラインドbaachikaruburaindo' },
//     { label: '室内窓', word: 'しつないまどシツナイマドshitsunaimado' },
//     { label: 'アイアン手摺', word: 'あいあんてすりアイアンテスリaiantesuri' },
//     { label: 'スケルトン階段', word: 'すけるとんかいだんスケルトンカイダンsukerutonkaidan' },

//     // --- 内装・仕上げ・素材 ---
//     { label: '無垢フローリング', word: 'むくふろーりんぐムクフローリングmukufurooringu' },
//     { label: '突板', word: 'つきいたツキイタtsukiita' },
//     { label: '挽板', word: 'ひきいたヒキイタhikiita' },
//     { label: 'クッションフロア', word: 'くっしょんふろあクッションフロアkusshonfuroa' },
//     { label: 'フロアタイル', word: 'ふろあたいるフロアタイルfuroatairu' },
//     { label: 'アクセントクロス', word: 'あくせんとくろすアクセントクロスakusentokurosu' },
//     { label: '漆喰', word: 'しっくいシックイshikkui' },
//     { label: '珪藻土', word: 'けいそうどケイソウドkeisoudo' },
//     { label: 'エコカラット', word: 'えこからっとエコカラットekokaratto' },
//     { label: 'モールテックス', word: 'もーるてっくすモールテックスmoorutekkusu' },
//     { label: 'ジョリパット', word: 'じょりぱっとジョリパットjoripatto' },
//     { label: 'ヘリンボーン', word: 'へりんぼーんヘリンボーンherinboon' },
//     { label: '真鍮', word: 'しんちゅうシンチュウshinchuu' },
//     { label: 'サブウェイタイル', word: 'さぶうぇいたいるサブウェイタイルsabuweitairu' },
//     { label: '名古屋モザイク', word: 'なごやもざいくナゴヤモザイクnagoyamozaiku' },

//     // --- キッチン・海外食洗機関連 ---
//     { label: 'アイランドキッチン', word: 'あいらんどきっちんアイランドキッチンairandokitchin' },
//     { label: 'ペニンシュラキッチン', word: 'ぺにんしゅらきっちんペニンシュラキッチンpeninshurakitchin' },
//     { label: 'セパレートキッチン', word: 'せぱれーときっちんセパレートキッチンsepareetokitchin' },
//     { label: '下がり天井', word: 'さがりてんじょうサガリテンジョウsagaritenjou' },
//     { label: 'カップボード', word: 'かっぷぼーどカップボードkappuboodo' },
//     { label: 'ミーレ', word: 'みーれミーレmiire' },
//     { label: 'ボッシュ', word: 'ぼっしゅボッシュbosshu' },
//     { label: 'ガゲナウ', word: 'がげなうガゲナウgagenau' },
//     { label: 'タッチレス水栓', word: 'たっちれすすいせんタッチレススイセンtatchiresusuisen' },

//     // --- 外構・エクステリア ---
//     { label: 'ウッドデッキ', word: 'うっどでっきウッドデッキuddodekki' },
//     { label: 'タイルデッキ', word: 'たいるでっきタイルデッキtairudekki' },
//     { label: 'カーポート', word: 'かーぽーとカーポートkaapooto' },
//     { label: 'ガレージ', word: 'がれーじガレージgareeji' },
//     { label: '宅配ボックス', word: 'たくはいぼっくすタクハイボックスtakuhaibokkusu' },
//     { label: 'シンボルツリー', word: 'しんぼるつりーシンボルツリーshinborutsurii' },
//     { label: '人工芝', word: 'じんこうしばジンコウシバjinkoushiba' },
//     { label: '目隠しフェンス', word: 'めかくしふぇんすメカクシフェンスmekakushifensu' },
//     { label: 'ラップサイディング', word: 'らっぷさいでぃんぐラップサイディングrappusaidingu' },
//     { label: 'ガルバリウム', word: 'がるばりうむガルバリウムgarubariumu' },

//     // --- 性能・電気設備 ---
//     { label: '高気密高断熱', word: 'こうきみつこうだんねつコウキミツコウダンネツkoukimitsukoudannetsu' },
//     { label: '全館空調', word: 'ぜんかんくうちょうゼンカンクウチョウzenkankuuchou' },
//     { label: '第一種換気', word: 'だいいっしゅかんきダイイッシュカンキdaiisshukanki' },
//     { label: '太陽光パネル', word: 'たいようこうぱねるタイヨウコウパネルtaiyoukoupaneru' },
//     { label: 'V2H', word: 'ぶいつーえいちブイツーエイチbuitsuueichi' },
//     { label: 'スマートホーム', word: 'すまーとほーむスマートホームsumaatohoomu' },
//     { label: 'ダウンライト', word: 'だうんらいとダウンライトdaunraito' },
//     { label: '間接照明', word: 'かんせつしょうめいカンセツショウメイkansetsushoumei' },
//     { label: 'ペンダントライト', word: 'ぺんだんとらいとペンダントライトpendantoraito' },
//     { label: '人感センサー', word: 'じんかんせんさージンカンセンサーjinkansensaa' },

//     // --- テイスト・スタイル ---
//     { label: '北欧インテリア', word: 'ほくおういんてりあホクオウインテリアhokuouinteria' },
//     { label: 'インテリア', word: 'いんてりあインテリアhokuouinteria' },
//     { label: 'ジャパンディ', word: 'じゃぱんでぃジャパンディjapandi' },
//     { label: 'インダストリアル', word: 'いんだすとりあるインダストリアルindasutoriaru' },
//     { label: 'モダン', word: 'もだんモダンmodan' },
//     { label: '和モダン', word: 'わもだんワモダンwamodan' },
//     { label: 'ミッドセンチュリー', word: 'みっどせんちゅりーミッドセンチュリーmiddosenchurii' },

//     // --- 建物種別・構造 ---
//     { label: '平屋', word: 'ひらやヒラヤhiraya' },
//     { label: 'シアタールーム', word: 'しあたーるーむシアタールーム' },
//     { label: '二階建て', word: 'にかいだてニカイダテnikaidate' },
//     { label: '三階建て', word: 'さんがいだてサンガイダテsangaidate' },
//     { label: '二世帯住宅', word: 'にせたいじゅうたくニセタイジュウタクnisetaijuutaku' },
//     { label: '店舗併用住宅', word: 'てんぽへいようじゅうたくテンポヘイヨウジュウタクtenpoheiyoujuutaku' },
//     { label: '木造軸組工法', word: 'もくぞうじくぐみこうほうモクゾウジクグミコウホウmokuzoujikugumikouhou' },
//     { label: 'ツーバイフォー', word: 'つーばいふぉーツーバイフォーtsuubaifoo' },
//     { label: '鉄骨造', word: 'てっこつぞうテッコツゾウtekkotsuzou' },
//     { label: 'コンクリート造', word: 'こんくりーとぞうコンクリートゾウkonkuriitozou' },

//     // --- 基礎・構造部材 ---
//     { label: 'ベタ基礎', word: 'べたぎそベタギソbetagiso' },
//     { label: '布基礎', word: 'ぬのぎそヌノギソnunogiso' },
//     { label: '地盤改良', word: 'じばんかいりょうジバンカイリョウjibankairyou' },
//     { label: '鋼管杭', word: 'こうかんぐいコウカングイkoukangui' },
//     { label: '柱', word: 'はしらハシラhashira' },
//     { label: '梁', word: 'はりハリhari' },
//     { label: '耐震等級', word: 'たいしんとうきゅうタイシントウキュウtaishintoukyuu' },
//     { label: '制震ダンパー', word: 'せいしんだんぱーセイシンダンパーseishindanpaa' },
//     { label: '断熱材', word: 'だんねつざいダンネツザイdannetsuzai' },
//     { label: 'グラスウール', word: 'ぐらすうーるグラスウールgurasuuuru' },
//     { label: '吹付断熱', word: 'ふきつけだんねつフキツケダンネツfukitsukedannetsu' },
//     { label: 'セルロースファイバー', word: 'せるろーすふぁいばーセルロースファイバーseruroosufaibaa' },

//     // --- 屋根・外装 ---
//     { label: '切妻屋根', word: 'きりづまやねキリヅマヤネkirizumayane' },
//     { label: '寄棟屋根', word: 'よせむねやねヨセムネヤネyosemuneyane' },
//     { label: '片流れ屋根', word: 'かたながれやねカタナガレヤネkatanagareyane' },
//     { label: '陸屋根', word: 'ろくやねロクヤネrokuyane' },
//     { label: '軒天', word: 'のきてんノキテンnokiten' },
//     { label: '破風', word: 'はふハフhafu' },
//     { label: '雨樋', word: 'あまどいアマドイamadoi' },
//     { label: '瓦', word: 'かわらカワラkawara' },
//     { label: 'コロニアル', word: 'ころにあるコロニアルkoroniaru' },
//     { label: 'アスファルトシングル', word: 'あすふぁるとしんぐるアスファルトシングルasufarutoshinguru' },
//     { label: 'ガルバリウム鋼板', word: 'がるばりうむこうはんガルバリウムコウハンgarubariumukouhan' },
//     { label: 'サイディング', word: 'さいでぃんぐサイディングsaidingu' },
//     { label: '塗り壁', word: 'ぬりかべヌリカベnurikabe' },
//     { label: 'タイル貼り', word: 'たいるばりタイルバリtairubari' },
//     { label: 'パワーボード', word: 'ぱわーぼーどパワーボードpawaaboodo' },

//     // --- 窓・開口部 ---
//     { label: '樹脂サッシ', word: 'じゅしさっしジュシサッシjushisasshi' },
//     { label: 'アルミ樹脂複合サッシ', word: 'あるみじゅしふくごうさっしアルミジュシフクゴウサッシarumijushifukugousasshi' },
//     { label: 'ペアガラス', word: 'ぺあがらすペアガラスpeagarasu' },
//     { label: 'トリプルガラス', word: 'とりぷるがらすトリプルガラスtoripurugarasu' },
//     { label: '掃き出し窓', word: 'はきだしまどハキダシマドhakidashimado' },
//     { label: '腰窓', word: 'こしまどコシマドkoshimado' },
//     { label: '縦すべり出し窓', word: 'たてすべりだしまどタテスベリダシマドtatesuberidashimado' },
//     { label: '横すべり出し窓', word: 'よこすべりだしまどヨコスベリダシマドyokosuberidashimado' },
//     { label: 'FIX窓', word: 'ふぃっくすまどフィックスマドfikkusumado' },
//     { label: '天窓', word: 'てんまどテンマドtenmado' },
//     { label: 'シャッター', word: 'しゃったーシャッターshattaa' },

//     // --- 外構・エクステリア（深掘り） ---
//     { label: '機能門柱', word: 'きのうもんちゅうキノウモンチュウkinoumonchuu' },
//     { label: '洗い出し', word: 'あらいだしアライダシaraidashi' },
//     { label: 'スタンプコンクリート', word: 'すたんぷこんくりーとスタンプコンクリートsutanpukonkuriito' },
//     { label: '土間コンクリート', word: 'どまこんくりーとドマコンクリートdomakonkuriito' },
//     { label: '砕石敷き', word: 'さいせきじきサイセキジキsaisekijiki' },
//     { label: '防草シート', word: 'ぼうそうしーとボウソウシートbousoushiito' },
//     { label: 'フェンス', word: 'ふぇんすフェンスfensu' },
//     { label: '境界目隠し', word: 'きょうかいめかくしキョウカイメカクシkyoukaimekakushi' },
//     { label: '枕木', word: 'まくらぎマクラギmakuragi' },
//     { label: '割栗石', word: 'わりぐりいしワリグリイシwariguriishi' },
//     { label: 'アプローチ', word: 'あぷろーちアプローチapuroochi' },
//     { label: '犬走り', word: 'いぬばしりイヌバシリinubashiri' },
//     { label: '立水栓', word: 'りっすいせんリッスイセンrissuisen' },
//     { label: '散水栓', word: 'さんすいせんサンスイセンsansuisen' },
//     { label: '物置', word: 'ものおきモノオキmonooki' },

//     // --- 土地・法規・その他 ---
//     { label: '建ぺい率', word: 'けんぺいりつケンペイリツkenpeiritsu' },
//     { label: '容積率', word: 'ようせきりつヨウセキリツyousekiritsu' },
//     { label: '北側斜線制限', word: 'きたがわしゃせんせいげんキタガワシャセンセイゲンkitagawashasenseigen' },
//     { label: '準防火地域', word: 'じゅんぼうかちいきジュンボウカチイキjunboukachiiki' },
//     { label: '長期優良住宅', word: 'ちょうきゆうりょうじゅうたくチョウキユウリョウジュウタクchoukiyuuryoujuutaku' },
//     { label: 'ZEH', word: 'ぜっちゼッチzetchi' },
//     { label: '地鎮祭', word: 'じちんさいジチンサイjichinsai' },
//     { label: '上棟式', word: 'じょうとうしきジョウトウシキjoutoushiki' },
//     { label: '施主検査', word: 'せしゅけんさセシュケンサseshukensa' },
//     { label: '固定資産税', word: 'こていしさんぜいコテイシサンゼイkoteishisanzei' },
//     { label: '住宅ローン減税', word: 'じゅうたくろーんげんぜいジュウタクローンゲンゼイjuutakuroongenzei' },

//     // --- 電気・設備スイッチ ---
//     { label: 'アドバンスシリーズ', word: 'あどばんすしりーずアドバンスシリーズadobansushiriizu' },
//     { label: 'ラフィーネア', word: 'らふぃーねあラフィーネアrafiinea' },
//     { label: 'アメリカンスイッチ', word: 'あめりかんすいっちアメリカンスイッチamerikansuitchi' },
//     { label: 'コンセント増設', word: 'こんせんとぞうせつコンセントゾウセツkonsentozousetsu' },
//     { label: '情報ボックス', word: 'じょうほうぼっくすジョウホウボックスjouhoubokkusu' },
//     { label: '分配器', word: 'ぶんぱいきブンパイキbunpaiki' },
//     { label: 'EVコンセント', word: 'いーぶいこんせんとイーヴイコンセントiibuikonsento' },

//     // --- 基本の部屋・空間 ---
//     { label: '玄関', word: 'げんかんゲンカンgenkan' },
//     { label: 'リビング', word: 'りびんぐリビングribingu' },
//     { label: 'ダイニング', word: 'だいにんぐダイニングdainingu' },
//     { label: 'キッチン', word: 'きっちんキッチンkitchin' },
//     { label: 'トイレ', word: 'といれトイレtoire' },
//     { label: '浴室', word: 'よくしつヨクシツyokushitsu' },
//     { label: 'お風呂', word: 'おふろオフロofuro' },
//     { label: '洗面所', word: 'せんめんじょセンメンジョsenmenjo' },
//     { label: '脱衣所', word: 'だついじょダツイジョdatsuijo' },
//     { label: '寝室', word: 'しんしつシンシツshinshitsu' },
//     { label: '子供部屋', word: 'こどもべやコドモベヤkodomobeya' },
//     { label: '和室', word: 'わしつワシツwashitsu' },
//     { label: '洋室', word: 'ようしつヨウシツyoushitsu' },
//     { label: '書斎', word: 'しょさいショサイshosai' },
//     { label: '階段', word: 'かいだんカイダンkaidan' },
//     { label: '廊下', word: 'ろうかロウカrouka' },
//     { label: 'ベランダ', word: 'べらんだベランダberanda' },
//     { label: 'バルコニー', word: 'ばるこにーバルコニーbarukonii' },
//     { label: '勝手口', word: 'かってぐちカッテグチkatteguchi' },

//     // --- 外部・エクステリア（基本） ---
//     { label: '駐車場', word: 'ちゅうしゃじょうチュウシャジョウchuushajou' },
//     { label: '駐輪場', word: 'ちゅうりんじょうチュウリンジョウchuurinjou' },
//     { label: '庭', word: 'にわニワniwa' },
//     { label: '門扉', word: 'もんぴモンピmonpi' },
//     { label: '外壁', word: 'がいへきガイヘキgaiheki' },
//     { label: '屋根', word: 'やねヤネyane' },
//     { label: '基礎', word: 'きそキソkiso' },
//     { label: 'ポスト', word: 'ぽすとポストposuto' },
//     { label: '表札', word: 'ひょうさつヒョウサツhyousatsu' },

//     // --- 収納 ---
//     { label: '収納', word: 'しゅうのうシュウノウshuunou' },
//     { label: 'クローゼット', word: 'くろーぜっとクローゼットkuroozetto' },
//     { label: '押入れ', word: 'おしいれオシイレoshiire' },
//     { label: '床下収納', word: 'ゆかしたしゅうのうユカシタシュウノウyukashitashuunou' },
//     { label: '屋根裏収納', word: 'やねうらしゅうのうヤネウラシュウノウyaneurashuunou' },
//     { label: '小屋裏収納', word: 'こやうらしゅうのうコヤウラシュウノウkoyaurashuunou' },
//     { label: '下駄箱', word: 'げたばこゲタバコgetabako' },
//     { label: 'シューズボックス', word: 'しゅーずぼっくすシューズボックスshuuzubokkusu' },

//     // --- 構造・建具（基本） ---
//     { label: '窓', word: 'まどマドmado' },
//     { label: '網戸', word: 'あみどアミドamido' },
//     { label: '雨戸', word: 'あまどアマドamado' },
//     { label: 'ドア', word: 'どあドアdoa' },
//     { label: '引き戸', word: 'ひきどヒキドhikido' },
//     { label: '開き戸', word: 'ひらきどヒラキドhirakido' },
//     { label: '折れ戸', word: 'おれどオレドoredo' },
//     { label: '天井', word: 'てんじょうテンジョウtenjou' },
//     { label: '床', word: 'ゆかユカyuka' },
//     { label: '壁', word: 'かべカベkabe' },

//     // --- 設備・機器（基本） ---
//     { label: '床暖房', word: 'ゆかだんぼうユカダンボウyukadanbou' },
//     { label: '浴室乾燥機', word: 'よくしつかんそうきヨクシツカンソウキyokushitsukansouki' },
//     { label: '食洗機', word: 'しょくせんきショクセンキshokusenki' },
//     { label: 'IHクッキングヒーター', word: 'あいえいちくっきんぐひーたーアイエイチクッキングヒーターaieichikukkinguhiitaa' },
//     { label: 'ガスコンロ', word: 'がすこんろガスコンロgasukonro' },
//     { label: '換気扇', word: 'かんきせんカンキセンkankisen' },
//     { label: 'レンジフード', word: 'れんじふーどレンジフードrenjifuudo' },
//     { label: '給湯器', word: 'きゅうとうきキュウトウキkyuutouki' },
//     { label: 'インターホン', word: 'いんたーほんインターホンintaahon' },
//     { label: '火災報知器', word: 'かさいほうちきカサイホウチキkasaihouchiki' },
//     { label: '分電盤', word: 'ぶんでんばんブンデンバンbundenban' },
//     { label: 'エアコン', word: 'えあこんエアコンeakon' },
//     { label: '床下換気口', word: 'ゆかしたかんきこうユカシタカンキコウyukashitakankikou' },

//     // --- 内装・インテリア（基本） ---
//     { label: '壁紙', word: 'かべがみカベガミkabegami' },
//     { label: 'クロス', word: 'くろすクロスkurosu' },
//     { label: 'フローリング', word: 'ふろーりんぐフローリングfurooringu' },
//     { label: '畳', word: 'たたみタタミtatami' },
//     { label: '障子', word: 'しょうじショウジshouji' },
//     { label: '襖', word: 'ふすまフスマfusuma' },
//     { label: 'カーテン', word: 'かーてんカーテンkaaten' },
//     { label: 'ロールスクリーン', word: 'ろーるすくりーんロールスクリーンroorusukuriin' },
//     { label: 'ブラインド', word: 'ぶらいんどブラインドburaindo' },
//     { label: '幅木', word: 'はばきハバキhabaki' },
//     { label: '廻り縁', word: 'まわりぶちマワリブチmawaribuchi' },

//     // --- 写真アングル・視点 ---
//     { label: '内観', word: 'ないかんナイカンnaikan' },
//     { label: '外観', word: 'がいかんガイカンgaikan' },
//     { label: '俯瞰', word: 'ふかんフカンfukan' },
//     { label: 'ファサード', word: 'ふぁさーどファサードfasaado' },
//     { label: '全体像', word: 'ぜんたいぞうゼンタイゾウzentaizou' },
//     { label: '寄り', word: 'よりヨリyori' },
//     { label: '引き', word: 'ひきヒキhiki' },
//     { label: 'ディテール', word: 'でぃてーるディテールditeeru' },
//     { label: 'アップ', word: 'あっぷアップappu' },
//     { label: '正面', word: 'しょうめんショウメンshoumen' },
//     { label: '横顔', word: 'よこがおヨコガオyokogao' },
//     { label: 'パノラマ', word: 'ぱのらまパノラマpanorama' },

//     // --- 時間帯・光の演出 ---
//     { label: '夜景', word: 'やけいヤケイyakei' },
//     { label: '夕景', word: 'ゆうけいユウケイyuukei' },
//     { label: '自然光', word: 'しぜんこうシゼンコウshizenkou' },
//     { label: 'ライトアップ', word: 'らいとあっぷライトアップraitoappu' },
//     { label: '逆光', word: 'ぎゃっこうギャッコウgyakkou' },
//     { label: '木漏れ日', word: 'こもれびコモレビkomorebi' },

//     // --- 写真の種別・状態 ---
//     { label: 'パース', word: 'ぱーすパースpaasu' },
//     { label: 'CG', word: 'しーじーシージーshiijii' },
//     { label: 'ルームツアー', word: 'るーむつあールームツアーruumutsuaa' },
//     { label: 'Web内覧会', word: 'うぇぶないらんかいウェブナイランカイwebunairankai' },
//     { label: '入居前', word: 'にゅうきょまえニュウキョマエnyuukyomae' },
//     { label: '入居後', word: 'にゅうきょごニュウキョゴnyuukyogo' },
//     { label: '生活感', word: 'せいかつかんセイカツカンseikatsukan' },
//     { label: '工事中', word: 'こうじちゅうコウジチュウkoujichuu' },
//     { label: '建築中', word: 'けんちくちゅうケンチクチュウkenchikuchuu' },
//     { label: '上棟', word: 'じょうとうジョウトウjoutou' },
//     { label: 'ビフォーアフター', word: 'びふぉーあふたービフォーアフターbifooafutaa' },
//     { label: '比較写真', word: 'ひかくしゃしんヒカクシャシンhikakushashin' },

//     // --- その他演出 ---
//     { label: 'カタログ風', word: 'かたろぐふうカタログフウkatarogufuu' },
//     { label: '生活動線', word: 'せいかつどうせんセイカツドウセンseikatsudousen' },
//     { label: '整理整頓', word: 'せいりせいとんセイリセイトンseiriseiton' },
//     { label: '飾り棚', word: 'かざりだなカザリダナkazaridana' },
//     { label: 'お気に入り', word: 'おきにいりオキニイリokiniiri' },

//     // --- キッチン・ダイニング（追加分） ---
//     { label: 'システムキッチン', word: 'しすてむきっちんシステムキッチンshisutemukitchin' },
//     { label: '造作キッチン', word: 'ぞうさくきっちんゾウサクキッチンzousakukitchin' },
//     { label: '壁付けキッチン', word: 'かべづけきっちんカベヅケキッチンkabedukekitchin' },
//     { label: '対面キッチン', word: 'たいめんきっちんタイメンキッチンtaimenkitchin' },
//     { label: '独立型キッチン', word: 'どくりつがたきっちんドクリツガタキッチンdokuritsugatakitchin' },
//     { label: 'L字キッチン', word: 'えるじきっちんエルジキッチンerujikitchin' },
//     { label: 'コの字キッチン', word: 'このじきっちんコノジキッチンkonojikitchin' },
//     { label: 'ワークトップ', word: 'わーくとっぷワークトップwaakutoppu' },
//     { label: 'シンク', word: 'しんくシンクshinku' },
//     { label: 'グースネック水栓', word: 'ぐーすねっくすいせんグースネックスイセンguusunekkusuisen' },
//     { label: '浄水器一体型水栓', word: 'じょうすいきいったいがたすいせんジョウスイキイッタイガタスイセンjousuikiittaigatasuisen' },
//     { label: '飾り棚', word: 'かざりだなカザリダナkazaridana' },

//     // --- 照明関係（追加分） ---
//     { label: '照明', word: 'しょうめいショウメイshoumei' },
//     { label: 'シーリングライト', word: 'しーりんぐらいとシーリングライトshiiringuraito' },
//     { label: 'ブラケットライト', word: 'ぶらけっとらいとブラケットライトburakettoraito' },
//     { label: 'スポットライト', word: 'すぽっとらいとスポットライトsupottoraito' },
//     { label: 'ダクトレール', word: 'だくとれーるダクトレールdakutoreeru' },
//     { label: 'フットライト', word: 'ふっとらいとフットライトfuttoraito' },
//     { label: 'シャンデリア', word: 'しゃんでりあシャンデリアshanderia' },
//     { label: 'コーヴ照明', word: 'こーゔしょうめいコーヴショウメイkoovushoumei' },
//     { label: 'コーニス照明', word: 'こーにすしょうめいコーニスショウメイkoonisushoumei' },
//     { label: '電球色', word: 'でんきゅうしょくデンキュウショクdenkyuushoku' },
//     { label: '温白色', word: 'おんぱくしょくオンパクショクonpakushoku' },
//     { label: '昼白色', word: 'ちゅうはくしょくチュウハクショクchuuhakushoku' },
//     { label: '調光', word: 'ちょうこうチョウコウchoukou' },

//     // --- 階段・空間の工夫（追加分） ---
//     { label: 'リビング階段', word: 'りびんぐかいだんリビングカイダンribingukaidan' },
//     { label: '折り返し階段', word: 'おりかえしかいだんオリカエシカイダンorikaeshikaidan' },
//     { label: '直線階段', word: 'ちょくせんかいだんチョクセンカイダンchokusenkaidan' },
//     { label: 'ストリップ階段', word: 'すとりっぷかいだんストリップカイダンsutorippukaidan' },
//     { label: '高天井', word: 'たかてんじょうタカテンジョウtakatenjou' },
//     { label: '折り上げ天井', word: 'おりあげてんじょうオリアゲテンジョウoriagetenjou' },
//     { label: 'スロープ', word: 'すろーぷスロープsuroopu' },
//     { label: 'バリアフリー', word: 'ばりあふりーバリアフリーbariafurii' },

//     // --- 水回り・サニタリー（追加分） ---
//     { label: '水回り', word: 'みずまわりミズマワリmizumawari' },
//     { label: 'サニタリー', word: 'さにたりーサニタリーsanitarii' },
//     { label: 'トイレ手洗い器', word: 'といれてあらいきトイレテアライキtoiretearaiki' },
//     { label: '洗面ボウル', word: 'せんめんぼうるセンメンボウルsenmenbouru' },
//     { label: 'タオル掛け', word: 'たおるかけタオルカケtaorukake' },
//     { label: 'タオルウォーマー', word: 'たおるうぉーまータオルウォーマーtaoruwoomaa' },
//     { label: 'ペーパーホルダー', word: 'ぺーぱーほるだーペーパーホルダーpeepaahorudaa' },
//     { label: 'ユニットバス', word: 'ゆにっとばすユニットバスyunittobasu' },
//     { label: '在来浴室', word: 'ざいらいよくしつザイライヨクシツzairaiyokushitsu' },
//     { label: 'ハーフユニットバス', word: 'はーふゆにっとばすハーフユニットバスhaafuyunittobasu' },

//     // --- 外観・外構（追加分） ---
//     { label: '外構', word: 'がいこうガイコウgaikou' },
//     { label: 'エクステリア', word: 'えくすてりあエクステリアekusuteria' },
//     { label: '植栽', word: 'しょくさいショクサイshokusai' },
//     { label: 'ルーバー', word: 'るーばールーバーruubaa' },
//     { label: 'スリット', word: 'すりっとスリットsuritto' },
//     { label: '妻飾り', word: 'つまかざりツマカザリtsumakazari' },

//     // --- テイスト・スタイル（追加分） ---
//     { label: 'ホテルライク', word: 'ほてるらいくホテルライクhoteruraiku' },
//     { label: 'カフェ風', word: 'かふぇふうカフェフウkafefuu' },
//     { label: 'ナチュラル', word: 'なちゅらるナチュラルnachuraru' },
//     { label: 'ヴィンテージ', word: 'ゔぃんてーじヴィンテージvinteeji' },
//     { label: 'ブルックリンスタイル', word: 'ぶるっくりんすたいるブルックリンスタイルburukkurinsutairu' },
//     { label: '西海岸風', word: 'にしかいがんふうニシカイガンフウnishikaiganfuu' },
//     { label: 'サーファーズハウス', word: 'さーふぁーずはうすサーファーズハウスsaafaazuhausu' },
//     { label: '南欧風', word: 'なんおうふうナンオウフウnanoufuu' },
//     { label: 'プロヴァンス風', word: 'ぷろゔぁんすふうプロヴァンスフウpurovansufuu' },
//     { label: 'アーバン', word: 'あーばんアーバンaaban' },

//     // --- 住宅スタイル（追加分） ---
//     { label: 'アーリーアメリカン', word: 'あーりーあめりかんアーリーアメリカンaariiamerikan' },
//     { label: 'カリフォルニアスタイル', word: 'かりふぉるにあすたいるカリフォルニアスタイルkariforuniasutairu' },
//     { label: 'カナディアン', word: 'かなでぃあんカナディアンkanadian' },
//     { label: 'アメリカンカントリー', word: 'あめりかんかんとりーアメリカンカントリーamerikankantorii' },
//     { label: 'ブリティッシュ', word: 'ぶりてぃっしゅブリティッシュburitisshu' },
//     { label: '輸入住宅', word: 'ゆにゅうじゅうたくユニュウジュウタクyunyuujuutaku' },
//     { label: 'プロバンス', word: 'ぷろばんすプロバンスpurobansu' },
//     { label: 'フレンチスタイル', word: 'ふれんちすたいるフレンチスタイルfurenchisutairu' },

//     // --- デザイン・雰囲気・抽象表現 ---
//     { label: 'ナチュラル', word: 'なちゅらるナチュラルnachuraru' },
//     { label: 'モダン', word: 'もだんモダンmodan' },
//     { label: 'ノワール', word: 'のわーるノワールnowaaru' },
//     { label: 'シック', word: 'しっくシックshikku' },
//     { label: 'ミニマル', word: 'みにまるミニマルminimaru' },
//     { label: 'ミニマリスト', word: 'みにまりすとミニマリストminimarisuto' },
//     { label: 'ラグジュアリー', word: 'らぐじゅありーラグジュアリーragujuarii' },
//     { label: 'スタイリッシュ', word: 'すたいりっしゅスタイリッシュsutairisshu' },
//     { label: 'エレガント', word: 'えれがんとエレガントereganto' },
//     { label: 'クラシック', word: 'くらしっくクラシックkurashikku' },
//     { label: 'アンティーク', word: 'あんてぃーくアンティークantiiku' },
//     { label: 'レトロ', word: 'れとろレトロretoro' },
//     { label: 'ポップ', word: 'ぽっぷポップpoppu' },
//     { label: 'モノトーン', word: 'ものとーんモノトーンmonotoon' },
//     { label: 'シンプル', word: 'しんぷるシンプルshinpuru' },
//     { label: 'シンプルモダン', word: 'しんぷるもだんシンプルモダンshinpurumodan' },
//     { label: '大人カジュアル', word: 'おとなかじゅあるオトナカジュアルotonakajuaru' },
//     { label: '開放的', word: 'かいほうてきカイホウテキkaihouteki' },
//     { label: '落ち着いた雰囲気', word: 'おちついたふんいきオチツイタフンイキochitsuitafuniki' },
//     { label: '温かみのある', word: 'あたたかみのあるアタタカミノアルatatakaminoaru' },

//     // --- 配色・ニュアンス ---
//     { label: 'ホワイトインテリア', word: 'ほわいといんてりあホワイトインテリアhowaitointeria' },
//     { label: 'ブラックインテリア', word: 'ぶらっくいんてりあブラックインテリアburakkuinteria' },
//     { label: 'グレーインテリア', word: 'ぐれーいんてりあグレーインテリアgureeinteria' },
//     { label: 'ニュアンスカラー', word: 'にゅあんすからーニュアンスカラーnyuansukaraa' },
//     { label: 'アースカラー', word: 'あーすからーアースカラーaasukaraa' },
//     { label: 'バイカラー', word: 'ばいからーバイカラーbaikaraa' },
//         { label: 'アーチ', word: 'あーちアーチaachi' }

// ];