export const databaseList = [
    {value: 'お客様名', id: 'customer_contacts_name', status: true},
    {value: '名前（かな）', id: 'customer_contacts_name_kana', status: true},
    {value: '担当営業', id: 'in_charge_user', status: true},
    {value: 'ステータス', id: 'status', status: true},
    {value: '顧客ランク', id: 'customized_input_01J82Z5F366ZQ897PXWF6H5ZAM', status: true},
    {value: '反響媒体', id: 'sales_promotion_name', status: true},
    {value: '問い合せのきっかけ', id: 'inquiry_reason', status: false},
    {value: '建築動機', id: 'house_hunting_motivation', status: false},
    {value: '新築計画', id: 'customer_desired_floor', status: false},
    {value: '入居時期', id: 'customer_desired_period', status: false},
    {value: '土地の状況', id: 'customer_desired_estate', status: false},
    // {value: 'お問い合わせ日', id: 'step_migration_item_01J82Z5F13B6QVM6X0TCWZHW99', status: true},
    // {value: '初回来場日', id: 'step_migration_item_01J82Z5F1GQB02S1DEBZPBFDW7', status: true},
    // {value: 'LINEグループ作成日', id: 'step_migration_item_01JSE75MPCGQW7V2MTY9VM4HXN', status: true},
    // {value: '事前審査', id: 'step_migration_item_01JSE0CRECT96FMYTZ1ZREC3QR', status: true},
    {value: '連絡先', id: 'contact', status: false},
    {value: '住所', id: 'address', status: false},
    {value: '土地の有無', id: 'has_owned_land', status: true},
    {value: '重視項目', id: 'customized_input_01JSE7DKY5RYY3T8T8NVR1AJMN', status: true},
    {value: '契約スケジュール', id: 'customized_input_01JSE7RNV3VK78YC2GYAG0554D', status: true},
    {value: '予算総額', id: 'budget', status: false},
    {value: '月々支払予算', id: 'monthly_repayment_amount', status: false},
    {value: '現居家賃', id: 'current_rent', status: false},
    {value: '現居光熱費', id: 'current_utility_costs', status: false},
    {value: '負債総額', id: 'current_loan_balance', status: false},
    {value: '現居契約形態', id: 'current_contract_type', status: false},
    {value: '雇用形態', id: 'customer_contacts_employment_type', status: false},
    {value: '勤務先名', id: 'customer_contacts_employer_name', status: false},
    {value: '勤務先住所', id: 'customer_contacts_employer_address', status: false},
    {value: '勤続年数', id: 'customer_contacts_years_of_service', status: false},
    {value: '年収', id: 'customer_contacts_annual_income', status: false},
    {value: '希望土地面積', id: 'desired_land_area', status: false},
    {value: '土地予算', id: 'land_budget', status: false},
    {value: '建設予定地', id: 'planned_construction_site', status: false},
    {value: '面談時アンケート', id: 'customized_input_01J95TC6KEES87F0YXH29AJP7K', status: false},
    {value: '備考', id: 'remarks', status: false},
    {value: '商談ステップ', id: 'interview_status', status: true},
    {value: '架電状況', id: 'call_status', status: true},
];
